### ISSUE TITLE
Create VM - Internal Server Error

### ISSUE THREAD

**Issue by mkuai** [SEI-AMS/pycloud#5]
I'm trying to "Create New VM Image" using Cloudlet Manager. After importing a blank VM, when I click "Save from SVM", it shows the error "There was a problem saving SVM: Internal Server Error". Can you help me figure it out? Below is the log message I got from Cloudlet Manager:

---

Exception happened during processing of request from ('127.0.0.1', 60980)
Traceback (most recent call last):
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in **init**
    self.handle()
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/paste/httpserver.py", line 306, in wsgi_execute
    for chunk in result:
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/paste/registry.py", line 409, in streaming_iter
    for item in self.application(environ, start_response):
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/beaker/middleware.py", line 155, in **call**
    return self.wrap_app(environ, session_start_response)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/routes/middleware.py", line 136, in **call**
    response = self.app(environ, start_response)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 103, in **call**
    response = self.dispatch(controller, environ, start_response)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/wsgiapp.py", line 313, in dispatch
    return controller(environ, start_response)
  File "/home/wiman/pycloud/pycloud/pycloud/pylons/lib/base.py", line 53, in **call**
    ret = WSGIController.**call**(self, environ, start_response)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 214, in **call**
    response = self._dispatch_call()
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 164, in _dispatch_call
    response = self._inspect_call(func)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 107, in _inspect_call
    result = self._perform_call(func, args)
  File "/home/wiman/pycloud/env/local/lib/python2.7/site-packages/pylons/controllers/core.py", line 57, in _perform_call
    return func(*_args)
  File "/home/wiman/pycloud/pycloud/pycloud/pylons/lib/util.py", line 100, in _asjson
    return _handler(f(_args, **kwargs))
TypeError: GET_saveInstanceToRoot() takes exactly 2 arguments (1 given)

**Comment by sebastian-echeverria** [comment]
There are a couple of known errors in the VM creation process in the master branch. Most of these have been fixed in our current feature branch. Let me check if this is the case, and I can backport the fix to the master branch through a hotfix branch.

Btw, if this is related to issue #4 , creating the VM from Cloudlet Manager should not change what you are seeing when sending a message from Speech App to its Server, as this communication happens between app and server, directly. So any issues you see are related to what you set up inside the VM, not to the creation of the VM itself. Well, if there was a bug in the port reported back to the app from pycloud, or in the way port forwarding is set up in the VM, it could affect that communication, but it is not likely.

**Comment by sebastian-echeverria** [comment]
Ok, a new hotfix branch was created, hotfix-vmcreation, that fixes the issue you just indicated here with VM creation, plus a few more I backported from a newer in-development branch (details in 05f0ceeb01cce367fe9d03681c265458e3bae300). This hotfix branch also includes the previous hotfix created for issue #4. Let me know if this works for you.

**Comment by mkuai** [comment]
The new hotfix-vmcreation is working well. Now I can obtain the .lqs file from data/svmcache folder. Thanks!
